### PR TITLE
added support for VNC Authentication using OpenSSL

### PR DESCRIPTION
**Pull request by prueckl**

### CODE REVIEW

**Comment by uwerat** [comment]
Concerning password/servername: bot are global settings and can't differ between servers or clients - at least not with the implementation provided. Then I would prefer not to copy them to every instance and use the getter of the VNC namespace, when needed. Makes the code IMHO more readable.

**Comment by uwerat** [comment]
The implementation of encrypt_rfbdes looks like being copied from some project implemented in C. If true we need to be aware of its license.

But in the end it is not that important - I will reimplement the sequence in a in a more C++ anyway.

**Comment by uwerat** [comment]
Did a quick check of the Qt code if we can get rid of having to deal with different OpenSSL versions. All I found is QCryptographicHash ( https://codebrowser.dev/qt5/qtbase/src/corelib/tools/qcryptographichash.cpp.html ). Might be useful for authentications available >= RFB V3.7 but not for DES en/decryption.

**Comment by prueckl** [comment]
Concerning password/servername: I refectored the code so that the client refers to the server instead of keeping a copy of the name/passwort itself.

**Comment by uwerat** [comment]
> Concerning password/servername: I refactored the code so that the client refers to the server instead of keeping a copy of the name/password itself.

Why having the copies in the server - name/password are available from the VNC namespace. Do you have a future use case in mind, where you need different settings for different windows ( = servers ) ?

**Comment by prueckl** [comment]
The code for encrypt_rfbdes was taken from
https://github.com/LibVNC/libvncserver/blob/master/src/common/crypto_openssl.c#L72

But thats just how the OpenSSL API works. I wrote my own implementation before, but after Update to OpenSSL v3 it failed because DES isn't supported anymore out of the box. So you have to load the "legacy" provider explicitly.

**Comment by prueckl** [comment]
> > Concerning password/servername: I refactored the code so that the client refers to the server instead of keeping a copy of the name/password itself.
> 
> Why having the copies in the server - name/password are available from the VNC namespace. Do you have a future use case in mind, where you need different settings for different windows ( = servers ) ?

Do you mean that the client should reference the password/name by using the global Vnc::password()/Vnc::name() function?

**Comment by uwerat** [comment]
> The code for encrypt_rfbdes was taken from https://github.com/LibVNC/libvncserver/blob/master/src/common/crypto_openssl.c#L72

This is GPL code what is more restrictive than the BSD license of vnc-eglfs. Usually no problem as it is no library but as the code is a triviality I would prefer not to use it.

Should be easy to replace it with a C++ implementation, where a helper class is used, that does the deconstructions in its destructor - instead of using gotos.

**Comment by uwerat** [comment]
> > > Concerning password/servername: I refactored the code so that the client refers to the server instead of keeping a copy of the name/password itself.
> > 
> > 
> > Why having the copies in the server - name/password are available from the VNC namespace. Do you have a future use case in mind, where you need different settings for different windows ( = servers ) ?
> 
> Do you mean that the client should reference the password/name by using the global Vnc::password()/Vnc::name() function?

Yes exactly - or did I miss something ?

**Comment by prueckl** [comment]
I refactored to code to use the global Vnc::password()/Vnc::name() functions.
The refactoring of the encrypt_des function is up to you.

**Comment by uwerat** [comment]
Thanks a lot for this valuable contribution. Will merge the pull request in the next days.

**Pull request merged**
